### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by tpepper** [s-rusev/github-contribution-appreciation#5]
create an initial contributor guide

**Comment by iyovcheva** [comment]
https://github.com/s-rusev/github-contribution-appreciation/commit/8d34b7228825a708a1711c4f908aecca20b9586e

**Comment by iyovcheva** [comment]
Closing with https://github.com/s-rusev/github-contribution-appreciation/commit/2b10d715c008cbd79297dd53ebd4048e775ee11b
